# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  hooks:
    pre: ./hack/before_release.sh {{ .Tag }}
  main: ./cmd/manager/main.go
  binary: yaks
  ldflags: -X github.com/citrusframework/yaks/version.Version={{ .Tag }}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - 386
  - arm64
  ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
- dockerfile: ./build/Dockerfile.release
  extra_files:
  - build
  image_templates:
  - 'docker.io/yaks/yaks:{{ .Tag }}'
  - 'docker.io/yaks/yaks:v{{ .Major }}.{{ .Minor }}'
  - 'docker.io/yaks/yaks:latest'
